spring:
  application:
    name: pharos-server
  config:
    import: optional:file:./.env[.properties],optional:file:../.env[.properties]
  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver # Explicitly tells Spring it's Postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080